### ISSUE TITLE
Erros na instalação

### ISSUE THREAD

**Issue by joaomnb** [jlopes60/eXist#1]
A instalação produz vários erros, e termina com a mensagem "Console installation FAILED".

Output do terminal: [output.txt](https://github.com/jlopes60/eXist/files/807546/output.txt)

Alguma ideia?

**Comment by jlopes60** [comment]
É estranho, porque eu consegui (em Ubuntu 16.06 LTS) com a mesma configuração. 
Olhando para o seu log, parece que, mesmo com todos as mensagens de erro, conseguiu criar a VM.
Depois de `vagrant up`, experimente fazer `vagrant ssh` para ver se entra na máquina e se a bd fica disponível em http://localhost:8080/exist

**Comment by joaomnb** [comment]
Confirmo, realmente a instalação resultou, apesar dos erros! Apenas só é possível aceder à bd depois de executar o comando `vagrant ssh`, que eu não tinha executado. É também preciso usar a porta 18080 em vez de 8080.

Problema resolvido! Obrigado!
